### ISSUE TITLE
Jupyter Lab as a Desktop Application 

### ISSUE THREAD

**Issue by sabinomaggi** [croach/blog#2]
Hi Christoper,
great tip, indeed, works perfectly. However, I get a huge amount of these warnings
`[warn] kevent: Invalid argument`
which is quite annoying. Any suggestion on how to avoid them?

**Comment by croach** [comment]
Hi Sabino,

I'm sorry, but I don't see that warning when running Jupyter Lab on my machine, so I can't help you out with your issue. Does this only happen when running jupyter lab using Chrome's headless mode, or does it happen when you run jupyter lab regularly as well?

Christopher

**Comment by sabinomaggi** [comment]
Hi Christoper,
the warning appears only when using Chrome's headless mode, if I run jupyter lab in a plain browser window everything works as expected. You can check [this short video](https://drive.google.com/open?id=12RMqDMSUQxw-BLFk90_EOydn6aI-p-NR).

**Comment by sabinomaggi** [comment]
Thanks for the tip, I didn't even notice the `pythonw` command. It seems an anaconda _feature_  (well...!), there is a [long thread here](https://github.com/ContinuumIO/anaconda-issues/issues/199) about the problems it gives under macOS. 
Now I must check how to avoid calling `pythonw` instead of plain `python`, but I think you have found the issue.

**Comment by sabinomaggi** [comment]
As a quick fix for macOS, I have copied the the `pythonw` script (the full path is ~/anaconda/bin/pythonw) into my personal `~/bin/` directory (any directory located _before_ `$HOME/anaconda/bin` in the $PATH environment variable would work equally well), changing the second line of the script to `$HOME/anaconda/bin/python "$@"`, and now everything works beutifully, without any "[warn] kevent: Invalid argument" warning.

Next step will be to remove anaconda completely (the whole thing is a mess and I never use Anaconda-Navigator which seems not to be well synchronized with conda updates from the command line), substituting it with miniconda or possibly going back to using the plain old pip/virtualenv.
